### ISSUE TITLE
Change to Site Pop-up/info

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#1]
Replace the current mock-up pop-up with 3 tabs with a single ESRI default pop-up containing the "Location information"

and in that popup 2 buttons that open different modals

one button "[fa-line-chart] Charts" which opens a Modal containing the applicable Charts for the location

one button "[fa-table] Full Trend Results" which opens the table view of all trend results for that location.

**Comment by njestes** [comment]
@HansVraga I'm actually thinking I'll go with the LobiPanel (thingy used on fim-js) for this so I can control more with the initial popup. It won't have the little triangle that points directly at the site, but we can probably convince them that this is a more customizable solution and can highlight the selected site like we do in the GW trends mapper. And if we add functionality to see the info for more than one site at a time, this will be easier to deal with.

**Comment by njestes** [comment]
added popup and buttons with #4 

next to create and make functional the modals.

**Comment by njestes** [comment]
Completed with #5
