### ISSUE TITLE
User Guide cleanup

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#100]
- [x] Tweak Layout to "clean it up" - perhaps swap text/images so text is all aligned on the left-hand side, another suggestion was to outline individual entries. Bold the names of the features discussed for each blurb
- [x] Rename the "Icons" tab and title to "Legend" 
- [x] Update Text/Entry as directed by Lori (will link to this once available)
- [x] switch Trend period screenshot to one with all four trend periods

**Comment by mitchas** [comment]
> Update Text/Entry as directed by Lori (will link to this once available) 

What is this?

**Comment by njestes** [comment]
@mitchas I think they mean the initial modal that loads when visiting the site. @HansVraga can you clarify?

**Comment by HansVraga** [comment]
Nah, I mean just the ever-changing User Guide content here. I think this issue can be closed and we can track any further edits to this section of the site elsewhere.
