### ISSUE TITLE
Link to the User Guide - Legend Tab from the Map Legend "Trend Result" area

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#101]
Add a button next to the "Trend Result" region of the Legend that will open the User Guide modal on the Legend Tab (so the user can see what the icons mean). Perhaps a tiny "book" icon just like the one used for the User Guide?

**Comment by mitchas** [comment]
Can't do this. Looks like you can't add HTML to the inside of the legend - it's all ESRI defaults that can only be styled with CSS - not added to. Something could go above or below, but that would be kind of pointless when the actual "User guide" button is right above.

**Comment by njestes** [comment]
@mitchas I totally agree. If they absolutely have to have it, then we can stick it above I guess. But let's ignore it and see if they still care. @HansVraga that cool?

**Comment by HansVraga** [comment]
This was a common point of feedback from the group.
What about additional text in the Legend (for more info, see User Guide)?

Can we cheat? I presume the ESRI legend is populated from the map services - can we put a link in there?

**Comment by njestes** [comment]
So we can't really put it "in" the legend as @mitchas says, but we can put things above it. The map services can't really carry that sort of info through. Or at least it would be a hack not worth the time right now.
