### ISSUE TITLE
Add Results Table Download

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#110]
Add the ability for the user to download a .csv of the data shown in the results table.

**Comment by njestes** [comment]
@mitchas if you want to add the button, icon, etc., I can take care of the building the file and initiating the download

**Comment by njestes** [comment]
I would add the button up top either next to the title or over by the "X". Open to other ideas though.

**Comment by mitchas** [comment]
Button there ready for you on branch mitch_issues01-13

**Comment by njestes** [comment]
added with #128
