### ISSUE TITLE
Site information for pesticide and aquatic ecology sites

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#150]
From Lori
>Site information – I noticed I didn’t give you drainage areas for pesticide and aquatic ecology sites. We are also about to publish new (slightly different) drainage areas for some of the other sites. I’ve attached here a file from James Falcone that has our final drainage areas (still in sq km) for all sites. Can you merge that in and use these for all constituents? Look at column E in the attached file sites1530-dec1-2016-short.xlsx.

**Comment by HansVraga** [comment]
We have a "We think you guys should do the merger and pass us all the info merged" option if we want to take it.

**Comment by njestes** [comment]
Done and done
