### ISSUE TITLE
Expand number of tracked click events

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#198]
With upcoming press release, we've been asked to get some good analytics on this site usage.
Look to track printing, Geosearch, and (if possible) the layer filters.

( @lprivette may have additional events )

**Comment by lprivette** [comment]
For reference and as an example, here's a spreadsheet of the events tracked in CRSRA https://docs.google.com/spreadsheets/d/1-qmqzGU3zk2j5p36MLvsUp__Q3DpCXTVCqs6YeibGs4/edit#gid=0

**Comment by lprivette** [comment]
Events being tracked for NAWQA SW Trends https://docs.google.com/spreadsheets/d/15LMPqJmzWDrqRqZqK_CM-cR_y-CTRy2aVlIOriPsW78/edit

Will email Freddie about getting on the analytics.usa.gov site once script is in live app.
