### ISSUE TITLE
FINAL CITATION

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#222]
Here's the final citation that needs updated:
Oelsner, G.P., Sprague, L.A., Murphy, J.C., Zuellig, R.E., Johnson, H.M., Ryberg, K.R., Falcone, J.A., Stets, E.G., Vecchia, A.V., Riskin, M.L., De Cicco, L.A., Mills, T.J., and Farmer, W.H., 2017, Water-quality trends in the Nation’s rivers and streams, 1972–2012—Data preparation, statistical methods, and trend results: U.S. Geological Survey Scientific Investigations Report 2017–5006, 136 p., https://doi.org/10.3133/sir20175006.

This update is needed in the following locations:

- [x] 1. About > Partner Organizations (at the end)
- [x] 2. User guide > Explanation (near the end)
- [x] 3. FAQ #2
- [x] 4. FAQ #19
- [x] 5. FAQ #26
- [x] 6. FAQ #28

**Comment by njestes** [comment]
Clarified with Lori, only changing "in press" to "136 p., https://doi.org/10.3133/sir20175006"
