### ISSUE TITLE
Symbols getting cut off in print view

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#242]
https://gis.wim.usgs.gov/arcgis/rest/directories/arcgisoutput/Utilities/PrintingTools_GPServer/_ags_745d979aac2e4784be5539232db44e0f.pdf

[_ags_745d979aac2e4784be5539232db44e0f.pdf](https://github.com/USGS-WiM/nawqa-sw-trends/files/1115495/_ags_745d979aac2e4784be5539232db44e0f.pdf)

**Comment by lprivette** [comment]
I can't recreate this.  When you get a chance @HansVraga can you try again and see if there are steps to recreate it?

**Comment by HansVraga** [comment]
Yeah I can't recreate either. Let's close this and when you update Prod with the addition of the explanation we'll ping Lori and let her know.
