### ISSUE TITLE
Explanation in Print View

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#244]
when you "print" a PDF, it doesn't include an explanation of the symbols.

Can this be added?

**Comment by njestes** [comment]
Definitely. Strange because I think it was working at one point.

**Comment by lprivette** [comment]
The data source was missing for the explanation which maybe was messing it up. So I just converted it to a graphic. Does that work? Looks like dis now. 
![image](https://user-images.githubusercontent.com/23640741/31146767-a49eb1a6-a855-11e7-941f-14647eab2029.png)
