### ISSUE TITLE
need to access png images on nawqatrends S3 bucket via https from within the app

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/nawqa-sw-trends#245]
Another option:

Maybe we already have an https ready S3 bucket for these things. I can put the images there if need be.

**Comment by aaronstephenson** [comment]
If the images are within the same folder as the app, you could just use relative references. Otherwise, you could use the absolute path including the FQDN (which would route the traffic back thru Toad). Or, you could use the default S3 URL and use S3's SSL cert, for example:

https://s3.amazonaws.com/nawqatrends.wim.usgs.gov/nawqaimages/fwsLogo.png

**Comment by njestes** [comment]
I think the app is located on Toad, so the we'd be hosting them on Toad going that way (the same folder as the app way, that is). So, I think I'll try out that last URL structure you have there. I'll let you know...

**Comment by aaronstephenson** [comment]
Oh, the app is on Toad but the images are on S3? Sorry, I didn't realize that. In that case, we could just put a simple reverse proxy rule in the nawqatrends "website" in IIS. Easy peasy.

**Comment by njestes** [comment]
I just implemented this structure URL -> 

https://s3.amazonaws.com/nawqatrends.wim.usgs.gov/nawqaimages/fwsLogo.png 

and it seems good to go. Would there be a benefit to using the reverse proxy instead or is it six of one, half dozen of the other?

**Comment by aaronstephenson** [comment]
I'm fine with either. The only potential negative I see with using the direct S3 URL is that someone might see it in your source code. But totally your call.

**Comment by njestes** [comment]
The images are also meant to be clicked and opened in new tabs, so they would see it there. I don't have any problem with that, I don't think. But I might not be seeing all the possible issues with that.

**Comment by aaronstephenson** [comment]
Maybe it's just a "branding" o r"professional/polished" thing... do we want them to know we're using S3, or just the app's proper URL? Maybe something to ask the whole group.

**Comment by njestes** [comment]
I'm good with the reverse proxy thing. Set 'er up and see how it works?

**Comment by aaronstephenson** [comment]
Reverse proxy is enabled.

**Comment by njestes** [comment]
So, I'm looking for this: https://s3.amazonaws.com/nawqatrends.wim.usgs.gov/charts/Total%20Phosphorus_06741510/plotConcPred.png
to convert to this:
https://nawqatrends.wim.usgs.gov/charts/Total%20Phosphorus_06741510/plotConcPred.png

Seems like it's not quite there, though the https is happy, it's returning a 404

it's a 'charts' 'directory' at the root of the bucket

**Comment by aaronstephenson** [comment]
Oh sorry, I only set up the reverse proxy for /nawqaimages/. I just set one for /charts/ too. Try it again.

**Comment by njestes** [comment]
Closer, I think. Now, I'm getting the wim error page when I try this:

https://nawqatrends.wim.usgs.gov/charts/Total%20Phosphorus_06741510/plotFluxPred.png

This still works:

https://s3.amazonaws.com/nawqatrends.wim.usgs.gov/charts/Total%20Phosphorus_06741510/plotFluxPred.png

**Comment by aaronstephenson** [comment]
I don't see that sub folder in S3. Just ~300 Alkalinities.

**Comment by njestes** [comment]
Might just be a refresh, still updating thing. This works:

https://s3.amazonaws.com/nawqatrends.wim.usgs.gov/charts/Total%20Phosphorus_06741510/plotFluxPred.png

**Comment by aaronstephenson** [comment]
I think that space might be screwing things up. Do you have an example without a space?

**Comment by njestes** [comment]
https://nawqatrends.wim.usgs.gov/charts/Alkalinity_09315000_4931276/plotFluxHistBoot.png

**Comment by aaronstephenson** [comment]
Bah, I give up. I can't figure out why the reverse proxy isn't working. Feel free to use the direct S3 URL. Sorry about the hold up.

**Comment by njestes** [comment]
cool. I'll code that up.
