### ISSUE TITLE
Add additional Analytics events

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#253]
The cooperator is interested in capturing this:
>Would it be possible to determine which chemicals people are looking at the most in the mapper, by looking at the analytics?  

This issue is to add hooks to capture what filters people set in the application

**Comment by jprokopec** [comment]
@lprivette can you make sure this comment is addressed in the analytics and as lookerstudio dashboard made? Thank you!

**Comment by ghost** [comment]
Closing due to GitLab migration.
