### ISSUE TITLE
Chrome/Android gestures not working

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#263]
App looks pretty on Chrome/Android, but drag to pan, pinch to zoom gestures do not currently work for me on Android/Chrome.

@ChadFanguy-usgs wonders if updating the ESRI API for JS will fix this.

**Comment by jprokopec** [comment]
Seems to be worse now? Chrome on an Android
![image](https://github.com/user-attachments/assets/bafb2bd5-f6f8-4285-86a7-88c7b69f8182)

**Comment by ghost** [comment]
Closing due to GitLab migration.
