### ISSUE TITLE
update version in About

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#266]
Application Version should match version

**Comment by jprokopec** [comment]
Double check versioning. Currently displaying Version 1.2.3
![image](https://github.com/user-attachments/assets/909f678d-2841-4410-ba18-a74373f90909)

**Comment by jprokopec** [comment]
Update Disclaimers as well https://www.usgs.gov/about/organization/science-support/office-science-quality-and-integrity/fundamental-science-5

**Comment by ghost** [comment]
Closing due to GitLab migration.
