### ISSUE TITLE
Remediate Vulnerability: Vulnerable Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/nawqa-sw-trends#267]
Acunetix scan reports this app is using jQuery 1.12.4 and should be updated. This is a Medium vulnerability and should be a priority.

**Comment by aaronstephenson** [comment]
Here's the relevant part of the report:

![image](https://user-images.githubusercontent.com/8713712/134226885-965f2994-8327-490d-8a55-2d42d2788f81.png)

**Comment by aaronstephenson** [comment]
I was just reviewing vulnerabilities today and noticed this issue is still open. Were you able to remediate this one @njestes?

**Comment by njestes** [comment]
Took me SO MUCH longer (a few hours today) than I wanted it to, but finally taken care of @aaronstephenson

**Comment by aaronstephenson** [comment]
Thanks!
