### ISSUE TITLE
Make adjustments to symbols for no trend direction

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#50]
The Yellow Circles are hard to see, and can be confused with the city circles. 
Team asked to keep the "Circle" shape. See if we can adjust color or add a dark outline to the circle (or both).

**Comment by njestes** [comment]
Got something up. Includes and darker outline, they are slightly larger and there is a circle in the middle. Pretty easily distinguishable from the cities now
