### ISSUE TITLE
Enable https:// links in FAQ

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#62]

**Comment by mitchas** [comment]
Do you mean links between FAQs?

**Comment by HansVraga** [comment]
We expect some edits to the FAQ - but this task is simply to ensure that hyperlinks in the FAQ text are hyperlinks (and not just text).

**Comment by lprivette** [comment]
Under "FAQ Resources" (the last faq section), there are links that are not hyperlinks. This section looks like it's just citations though, unsure if that should effect whether we hyperlink it or not. I checked the entire FAQs and this was the only place I noticed the links being just text.

Some bad characters also sneaked into that section. Should that be another ticket?

**Comment by HansVraga** [comment]
Closing to open a new issue - Lots of new FAQ content.
