### ISSUE TITLE
print map option

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/nawqa-sw-trends#66]

**Comment by mitchas** [comment]
This is also possible with CSS if needed. I'm not sure what the easiest way would be, unless you know of something.

Could be weird with CSS though because the stuff that needs to be printed is floating in a modal..

**Comment by njestes** [comment]
in this case, I think they just want a map printed up like we have in this
mapper:

https://fws.wim.usgs.gov/wetlands/apps/wetlands-mapper/

This involves ArcGIS Server and a little mockup of a template. This'll be
easy as soon as I get around to it.

__________________________________

*Nick Estes*
WiM Senior Developer
Based in Davis, California (PST)

Web Informatics and Mapping (WiM)
Wisconsin Water Science Center
US Geological Survey
Middleton, WI

Phone: 608.821.3904
njestes@usgs.gov
wim.usgs.gov

**Comment by njestes** [comment]
use print modal with title already determined
