### ISSUE TITLE
changes to WRTDS plots pulled from ScienceBase

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#72]
From Lori:
>I've made a slight change to the list of WRTDS plots to pull from ScienceBase for the graphs tab.  They are: plotConcTime, boxConcMonth, plotConcPred, plotFluxPred, plotConcHistBoot, and plotFluxHistBoot.  Note the last two in red have changed from plotConcHist and plotFluxHist to plotConcHistBoot and plotFluxHistBoot since our last communication about this.  All of these are available as PNG on Science Base.

**Comment by njestes** [comment]
using new file names with #78
