### ISSUE TITLE
Results Table template and work

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#75]
From Lori:
>I've slightly modified the template for the table of results, and added some help text (maybe that can be added as hover text while someone is looking at the table?).  That information is in "template for table.xlsx".
Linked here: https://drive.google.com/open?id=0BygT1gkOzi3SeTFrSFEtQ0N5c21pT3VaNUdDYTRWMGctM2FF

We need to set up the table to match the template, and do the following (as per her document):

- [x] Use only one of the four trend periods shown in the column "Trend period".  So, for example, even if a trend is shown in the data files from 1993-2011, still show the field here as "1992-2012" so it will correspond to the map selection.
- [x] Use full name (not the acronym) for the aquatic ecology name in the column "Constituent"
- [x] All ecology variables will have "Metric (climate normalized)" in Column B
- [x] Confidence intervals  in column K will vary by model.  All of those for WRTDS are "90 percent confidence interval".   All of those for SEAWAVE (the pesticides) are "95 percent confidence interval".  All of those for aquatic ecology are "Not available".

**Comment by njestes** [comment]
It doesn't look great, but it's in there
