### ISSUE TITLE
Help Text for Results Table

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#76]
Lori has asked for mouseover text, but if possible, text that appears after clicking/tapping a "?" for each column would be preferable. Below is the text, pulled from the notes listed here: https://drive.google.com/open?id=0BygT1gkOzi3SeTFrSFEtQ0N5c21pT3VaNUdDYTRWMGctM2FF

- [ ] For column B: Concentration is the amount of the constituent in the stream.  Load is the mass of the constituent transported past the sampling point in a stream during a period of time.  A metric is an index calculated to represent a specific characteristic of aquatic communities.  Changes over time in water-quality concentration and load and changes in aquatic ecology-metrics can be strongly influenced by random and systematic variations in streamflow.  Flow normalization removes the variation in concentration, load, or metric that is due to variations in streamflow.  Changes over time in aquatic ecology metrics can also be strongly influenced by random and systematic variations in air temperature.  As a result, concentration and load trends are flow normalized; aquatic ecology trends are climate normalized (normalized for flow and(or) air temperature).  See FAQ #12 for more information.  (provide a hyperlink here if it makes sense)
- [ ] For column D: The likelihood-based approach is used as an alternative to the null-hypothesis significance testing  approach that is often used when reporting water-quality trends.  See FAQ #13 for more information.  (provide a hyperlink here if it makes sense)
- [ ] For columns H-J: The original units for each constituent and type are shown in the "Learn More" (provide link if it makes sense)
- [ ] For column K: A confidence interval is the interval that contains the true trend with the given likelihood. For example, for a 90% confidence interval, we can say we are 90% confident that the true trend is in the reported confidence interval, or that 90% of the hypothetically observed confidence intervals will hold the true trend.
- [ ] Hover text for columns E and H should say "Trends are reported for the full trend period.  They are not reported on a per year basis."

**Comment by HansVraga** [comment]
Need the table populated first before figuring out how to best add the help text, I think.
Also, is it possible to link directly to a FAQ item (and have it open with the specific accordion section open)? Same thing with linking to the "Learn More" tab of the About popup?

**Comment by HansVraga** [comment]
Assigning to Mitch even though I think progress on the table will likely need to be made first, so we can talk about how best to implement this help text - @mitchas have a method in mind?

**Comment by njestes** [comment]
Thinking now we'll add a "?" icon and when clicking that it'll open another modal or popup with the info for each column. Names of the columns are in row 2 of the above doc
