### ISSUE TITLE
Progress loader (when charts/tables clicked)

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/nawqa-sw-trends#83]

**Comment by njestes** [comment]
I'll put it into action once @mitchas has an image in there

**Comment by mitchas** [comment]
On you now @njestes - got a loader/div in the latest push to mitch_issues01-13.. I have in in the charts modal section. Do we need in in the table? Seems to load quickly there.

**Comment by njestes** [comment]
@mitchas got it working locally now. I do have an issue with the size of the loading image and it's div. it's pushed outside of the modal. probably a padding/margin thing that you could solve in less than 3 seconds, so I'll pass the ball back to you.

The table has some "loading..." text that they noticed and liked and yeah, it loads so fast usually that I think it will suffice for now.
