### ISSUE TITLE
Add functionality to view Chart/Graph PNGs at larger size

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#92]
The 2x3 layout for the charts that was requested looks nice, but are a bit tiny for a detailed look. We've been given freedom to enable viewing of these PNGs at a larger size in whatever means we think is best.

**Comment by mitchas** [comment]
Made it as simple as possible. Opens in a new tab. Pretty standard for Government sites... Also that way people can download/save them if needed.
